### ISSUE TITLE
Just wanted to say...

### ISSUE THREAD

**Issue by JairusSW** [isivisi/Chess.com#2]
Hey, thanks so much for making this! Chess.com was origianally just a quick project, but I'm so glad you extended it! Feel free to contribute and submit a pull request! As always, thank you!

Btw, I was wondering where to find the settings page...

**Comment by isivisi** [comment]
Sorry this is so late XD, you need to right click the tray icon to get to the settings

**Comment by JairusSW** [comment]
Oh, thanks! @isivisi .
Btw, if you switch it to a electron-forge project, it performs much faster.
The electron-builder is super slow. 😄
